{"timestamp": "2025-03-09 18:13", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-09 18:14", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-09 18:14", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-09 18:14", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x70d93754ded0>"}
{"timestamp": "2025-03-09 18:14", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-09 18:15", "level": "INFO", "instance": "bot", "message": "Fetching branch details for ID: 1"}
{"timestamp": "2025-03-09 18:15", "level": "INFO", "instance": "bot", "message": "Attempting to send photo from path: bot/config/logo.jpg"}
{"timestamp": "2025-03-09 18:15", "level": "ERROR", "instance": "bot", "message": "Error in show_branch_details: HTTP Client says - ClientOSError: [Errno 2] Can not write request body for http://telegram-bot-api:8081/bot8037850746:AAG6xtfRFugtpkkNoaitT8-mh1JLk1OM-Z8/sendPhoto", "stack_trace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py\", line 658, in write_bytes\n    await self.body.write(writer)\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/multipart.py\", line 1008, in write\n    await part.write(writer)\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/payload.py\", line 494, in write\n    chunk = await self._iter.__anext__()\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/types/input_file.py\", line 103, in read\n    async with aiofiles.open(self.path, \"rb\") as f:\n  File \"/usr/local/lib/python3.11/site-packages/aiofiles/base.py\", line 63, in __aenter__\n    return await self\n           ^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiofiles/base.py\", line 59, in __await__\n    self._obj = yield from self._coro.__await__()\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiofiles/threadpool/__init__.py\", line 92, in _open\n    f = await loop.run_in_executor(executor, cb)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'bot/config/logo.jpg'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 177, in make_request\n    async with session.post(\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/client.py\", line 1425, in __aenter__\n    self._resp: _RetType = await self._coro\n                           ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/client.py\", line 730, in _request\n    await resp.start(conn)\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py\", line 1059, in start\n    message, payload = await protocol.read()  # type: ignore[union-attr]\n                       ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/streams.py\", line 672, in read\n    await self._waiter\naiohttp.client_exceptions.ClientOSError: [Errno 2] Can not write request body for http://telegram-bot-api:8081/bot8037850746:AAG6xtfRFugtpkkNoaitT8-mh1JLk1OM-Z8/sendPhoto\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/bot/handlers/branch.py\", line 105, in show_branch_details\n    await call.message.answer_photo(\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/bot.py\", line 498, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 184, in make_request\n    raise TelegramNetworkError(method=method, message=f\"{type(e).__name__}: {e}\")\naiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 2] Can not write request body for http://telegram-bot-api:8081/bot8037850746:AAG6xtfRFugtpkkNoaitT8-mh1JLk1OM-Z8/sendPhoto"}
{"timestamp": "2025-03-09 18:16", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 00:28", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 00:29", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x7a32e35613d0>"}
{"timestamp": "2025-03-10 00:29", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 00:31", "level": "ERROR", "instance": "bot", "message": "Error in show_branch_details: HTTP Client says - ClientOSError: [Errno 2] Can not write request body for http://telegram-bot-api:8081/bot8037850746:AAG6xtfRFugtpkkNoaitT8-mh1JLk1OM-Z8/sendPhoto", "stack_trace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py\", line 658, in write_bytes\n    await self.body.write(writer)\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/multipart.py\", line 1008, in write\n    await part.write(writer)\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/payload.py\", line 494, in write\n    chunk = await self._iter.__anext__()\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/types/input_file.py\", line 103, in read\n    async with aiofiles.open(self.path, \"rb\") as f:\n  File \"/usr/local/lib/python3.11/site-packages/aiofiles/base.py\", line 63, in __aenter__\n    return await self\n           ^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiofiles/base.py\", line 59, in __await__\n    self._obj = yield from self._coro.__await__()\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiofiles/threadpool/__init__.py\", line 92, in _open\n    f = await loop.run_in_executor(executor, cb)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'bot/config/logo.jpg'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 177, in make_request\n    async with session.post(\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/client.py\", line 1425, in __aenter__\n    self._resp: _RetType = await self._coro\n                           ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/client.py\", line 730, in _request\n    await resp.start(conn)\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py\", line 1059, in start\n    message, payload = await protocol.read()  # type: ignore[union-attr]\n                       ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/streams.py\", line 672, in read\n    await self._waiter\naiohttp.client_exceptions.ClientOSError: [Errno 2] Can not write request body for http://telegram-bot-api:8081/bot8037850746:AAG6xtfRFugtpkkNoaitT8-mh1JLk1OM-Z8/sendPhoto\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/bot/handlers/branch.py\", line 104, in show_branch_details\n    await call.message.answer_photo(\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/bot.py\", line 498, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 184, in make_request\n    raise TelegramNetworkError(method=method, message=f\"{type(e).__name__}: {e}\")\naiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 2] Can not write request body for http://telegram-bot-api:8081/bot8037850746:AAG6xtfRFugtpkkNoaitT8-mh1JLk1OM-Z8/sendPhoto"}
{"timestamp": "2025-03-10 00:31", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 00:32", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 00:34", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x7f791b1e2bd0>"}
{"timestamp": "2025-03-10 00:34", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 00:35", "level": "ERROR", "instance": "bot", "message": "An unexpected error occurred.", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/back.py\", line 14, in back\n    await call.message.edit_text(\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/bot.py\", line 498, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 185, in make_request\n    response = self.check_response(\n               ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: there is no text in the message to edit"}
{"timestamp": "2025-03-10 00:36", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 00:36", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 00:37", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x797f193b0bd0>"}
{"timestamp": "2025-03-10 00:37", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 00:37", "level": "ERROR", "instance": "bot", "message": "An unexpected error occurred.", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/back.py\", line 14, in back\n    await call.message.edit_text(\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/bot.py\", line 498, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 185, in make_request\n    response = self.check_response(\n               ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: there is no text in the message to edit"}
{"timestamp": "2025-03-10 04:13", "level": "ERROR", "instance": "bot", "message": "An unexpected error occurred.", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/back.py\", line 14, in back\n    await call.message.edit_text(\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/bot.py\", line 498, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 185, in make_request\n    response = self.check_response(\n               ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: there is no text in the message to edit"}
{"timestamp": "2025-03-10 04:43", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 04:44", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 04:44", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x74662160cbd0>"}
{"timestamp": "2025-03-10 04:44", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 04:45", "level": "ERROR", "instance": "bot", "message": "Error in handle_back_button: Telegram server says - Bad Request: there is no text in the message to edit", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/branch.py\", line 144, in handle_back_button\n    await call.message.edit_text(\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/bot.py\", line 498, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 185, in make_request\n    response = self.check_response(\n               ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: there is no text in the message to edit"}
{"timestamp": "2025-03-10 04:46", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 04:47", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 04:48", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x7227239af590>"}
{"timestamp": "2025-03-10 04:48", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 04:48", "level": "ERROR", "instance": "bot", "message": "Error in delete_branch_handler: type object 'Cruds' has no attribute 'delete_branch'", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/branch.py\", line 121, in delete_branch_handler\n    success = await Cruds.delete_branch(branch_id)\n                    ^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'Cruds' has no attribute 'delete_branch'"}
{"timestamp": "2025-03-10 04:49", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 04:50", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 04:50", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x708fbbf641d0>"}
{"timestamp": "2025-03-10 04:50", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 04:51", "level": "ERROR", "instance": "bot", "message": "Error in delete_branch: name 'delete' is not defined", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/utils/database/crud.py\", line 227, in delete_branch\n    query = delete(Branch).where(Branch.id == branch_id)\n            ^^^^^^\nNameError: name 'delete' is not defined"}
{"timestamp": "2025-03-10 04:51", "level": "ERROR", "instance": "bot", "message": "Error in delete_branch: name 'delete' is not defined", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/utils/database/crud.py\", line 227, in delete_branch\n    query = delete(Branch).where(Branch.id == branch_id)\n            ^^^^^^\nNameError: name 'delete' is not defined"}
{"timestamp": "2025-03-10 04:52", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 04:53", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 04:53", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x7e8ccb893490>"}
{"timestamp": "2025-03-10 04:53", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 05:04", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:05", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:11", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:11", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:12", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:13", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:18", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:18", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:19", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x7f2d8757b550>"}
{"timestamp": "2025-03-10 05:19", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 05:20", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 05:20", "level": "INFO", "instance": "bot", "message": "show_user_branches handler ishga tushdi, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:20", "level": "ERROR", "instance": "bot", "message": "Error in show_branch_details: invalid literal for int() with base 10: 'user_1'", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/branch.py\", line 65, in show_branch_details\n    branch_id = int(call.data.replace(\"branch_detail_\", \"\"))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nValueError: invalid literal for int() with base 10: 'user_1'"}
{"timestamp": "2025-03-10 05:21", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:22", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:22", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x7f040e771250>"}
{"timestamp": "2025-03-10 05:22", "level": "ERROR", "instance": "bot", "message": "Lokalizatsiya kaliti 'text-branch-get_address' topilmadi!"}
{"timestamp": "2025-03-10 05:25", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:25", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:26", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x7d8a07deb610>"}
{"timestamp": "2025-03-10 05:44", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:45", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:45", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x700e078b1550>"}
{"timestamp": "2025-03-10 05:46", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 05:46", "level": "INFO", "instance": "bot", "message": "show_user_branches handler ishga tushdi, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:46", "level": "ERROR", "instance": "bot", "message": "Error in show_branch_details: invalid literal for int() with base 10: 'user_1'", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/branch.py\", line 65, in show_branch_details\n    branch_id = int(call.data.replace(\"branch_detail_\", \"\"))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nValueError: invalid literal for int() with base 10: 'user_1'"}
{"timestamp": "2025-03-10 05:48", "level": "INFO", "instance": "bot", "message": "show_user_branches handler ishga tushdi, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:49", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:49", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:49", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x70e68a393810>"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 05:50", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 05:50", "level": "ERROR", "instance": "bot", "message": "Error in show_branch_details: invalid literal for int() with base 10: 'user_1'", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/branch.py\", line 65, in show_branch_details\n    branch_id = int(call.data.replace(\"branch_detail_\", \"\"))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nValueError: invalid literal for int() with base 10: 'user_1'"}
{"timestamp": "2025-03-10 05:53", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:54", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:54", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 05:54", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:54", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 05:54", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type man"}
{"timestamp": "2025-03-10 05:54", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:55", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 05:55", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type man"}
{"timestamp": "2025-03-10 05:55", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:55", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x7df4a49c1bd0>"}
{"timestamp": "2025-03-10 05:56", "level": "INFO", "instance": "bot", "message": "Admin branch details called with callback_data: branch_detail_1"}
{"timestamp": "2025-03-10 05:56", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 05:56", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:56", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 05:56", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 05:56", "level": "INFO", "instance": "bot", "message": "show_user_branch_details called with callback_data: branch_detail_user_1"}
{"timestamp": "2025-03-10 05:56", "level": "INFO", "instance": "bot", "message": "Fetching branch with ID: 1"}
{"timestamp": "2025-03-10 05:56", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:56", "level": "ERROR", "instance": "bot", "message": "Error in show_user_branches: Telegram server says - Bad Request: there is no text in the message to edit", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/branch_user.py\", line 13, in show_user_branches\n    await call.message.edit_text(\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/bot.py\", line 498, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py\", line 185, in make_request\n    response = self.check_response(\n               ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: there is no text in the message to edit"}
{"timestamp": "2025-03-10 05:57", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 05:57", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:57", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: woman"}
{"timestamp": "2025-03-10 05:57", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type woman"}
{"timestamp": "2025-03-10 05:57", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:57", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 05:57", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 05:57", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 05:58", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 05:59", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 05:59", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x79dedd2ed7d0>"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "Admin branch details called with callback_data: branch_detail_1"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "show_user_branch_details called with callback_data: branch_detail_user_1"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "Fetching branch with ID: 1"}
{"timestamp": "2025-03-10 06:00", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:01", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 06:12", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type man"}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type man"}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:13", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x75e1277681d0>"}
{"timestamp": "2025-03-10 06:14", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:14", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:14", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 06:14", "level": "INFO", "instance": "bot", "message": "show_user_branch_details called with callback_data: branch_detail_user_1"}
{"timestamp": "2025-03-10 06:14", "level": "INFO", "instance": "bot", "message": "Fetching branch with ID: 1"}
{"timestamp": "2025-03-10 06:14", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:15", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:22", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:24", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:25", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:25", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:25", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:25", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type man"}
{"timestamp": "2025-03-10 06:25", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:25", "level": "ERROR", "instance": "bot", "message": "Error in show_user_branches: branchs_user() got an unexpected keyword argument 'is_admin'", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/branch_user.py\", line 16, in show_user_branches\n    reply_markup=btn.branchs_user(i18n=i18n, is_admin=False)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: branchs_user() got an unexpected keyword argument 'is_admin'"}
{"timestamp": "2025-03-10 06:25", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:26", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:26", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:27", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:27", "level": "ERROR", "instance": "bot", "message": "Error in filiallar_handler: branchs_user() got an unexpected keyword argument 'is_admin'", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/start.py\", line 58, in filiallar_handler\n    reply_markup=btn.branchs_user(i18n=i18n, is_admin=False)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: branchs_user() got an unexpected keyword argument 'is_admin'"}
{"timestamp": "2025-03-10 06:27", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:27", "level": "ERROR", "instance": "bot", "message": "Error in filiallar_handler: branchs_user() got an unexpected keyword argument 'is_admin'", "stack_trace": "Traceback (most recent call last):\n  File \"/app/bot/handlers/start.py\", line 58, in filiallar_handler\n    reply_markup=btn.branchs_user(i18n=i18n, is_admin=False)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: branchs_user() got an unexpected keyword argument 'is_admin'"}
{"timestamp": "2025-03-10 06:30", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:31", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:31", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:32", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:32", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:32", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:33", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:38", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type man"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type man"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type man"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: child"}
{"timestamp": "2025-03-10 06:39", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type child"}
{"timestamp": "2025-03-10 06:43", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:44", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:44", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x76cc8515e210>"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "Admin branch details called with callback_data: branch_detail_1"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branch_details called with callback_data: branch_detail_user_1"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "Fetching branch with ID: 1"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: child"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type child"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branch_details called with callback_data: branch_detail_user_1"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "Fetching branch with ID: 1"}
{"timestamp": "2025-03-10 06:45", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:47", "level": "INFO", "instance": "bot", "message": "Bot shutting down..."}
{"timestamp": "2025-03-10 06:47", "level": "INFO", "instance": "bot", "message": "Bot running..."}
{"timestamp": "2025-03-10 06:47", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:48", "level": "INFO", "instance": "bot", "message": "Foydalanuvchi tili: <fluentogram.src.impl.runner.TranslatorRunner object at 0x717f54d11710>"}
{"timestamp": "2025-03-10 06:48", "level": "INFO", "instance": "bot", "message": "Admin branch details called with callback_data: branch_detail_1"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "User 5773326948 requested filiallar"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "show_user_branch_details called with callback_data: branch_detail_user_1"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "Fetching branch with ID: 1"}
{"timestamp": "2025-03-10 06:49", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 06:51", "level": "INFO", "instance": "bot", "message": "User 7669700778 requested filiallar"}
{"timestamp": "2025-03-10 06:51", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 06:51", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 06:51", "level": "INFO", "instance": "bot", "message": "show_user_branch_details called with callback_data: branch_detail_user_1"}
{"timestamp": "2025-03-10 06:51", "level": "INFO", "instance": "bot", "message": "Fetching branch with ID: 1"}
{"timestamp": "2025-03-10 09:09", "level": "INFO", "instance": "bot", "message": "User 1732622354 requested filiallar"}
{"timestamp": "2025-03-10 09:09", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 09:09", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 09:24", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-10 09:24", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-10 09:25", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: man"}
{"timestamp": "2025-03-10 09:25", "level": "INFO", "instance": "bot", "message": "Found 1 branches for type man"}
{"timestamp": "2025-03-10 09:25", "level": "INFO", "instance": "bot", "message": "show_user_branch_details called with callback_data: branch_detail_user_1"}
{"timestamp": "2025-03-10 09:25", "level": "INFO", "instance": "bot", "message": "Fetching branch with ID: 1"}
{"timestamp": "2025-03-10 09:26", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-11 03:41", "level": "INFO", "instance": "bot", "message": "show_user_branch_list called for branch_type: child"}
{"timestamp": "2025-03-11 03:41", "level": "INFO", "instance": "bot", "message": "Found 0 branches for type child"}
{"timestamp": "2025-03-11 03:41", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
{"timestamp": "2025-03-11 03:41", "level": "INFO", "instance": "bot", "message": "User 5773326948 uchun menyuni yuborildi"}
{"timestamp": "2025-03-11 03:41", "level": "INFO", "instance": "bot", "message": "show_user_branches called by user 5773326948, callback_data: branchs_user"}
